"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta

"""Base class used by all hvac "api" classes."""
logger = ...
class VaultApiBase(metaclass=ABCMeta):
    """Base class for API endpoints."""
    def __init__(self, adapter) -> None:
        """Default api class constructor.

        :param adapter: Instance of :py:class:`hvac.adapters.Adapter`; used for performing HTTP requests.
        :type adapter: hvac.adapters.Adapter
        """
        ...
    


