"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta
from hvac.api.vault_api_base import VaultApiBase

logger = ...
class SystemBackendMixin(VaultApiBase, metaclass=ABCMeta):
    """Base class for System Backend API endpoints."""
    ...


