"""
This type stub file was generated by pyright.
"""

class VaultError(Exception):
    def __init__(self, message=..., errors=..., method=..., url=..., text=..., json=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @classmethod
    def from_status(cls, status_code: int, *args, **kwargs):
        ...
    


class InvalidRequest(VaultError):
    ...


class Unauthorized(VaultError):
    ...


class Forbidden(VaultError):
    ...


class InvalidPath(VaultError):
    ...


class RateLimitExceeded(VaultError):
    ...


class InternalServerError(VaultError):
    ...


class VaultNotInitialized(VaultError):
    ...


class VaultDown(VaultError):
    ...


class UnexpectedError(VaultError):
    ...


class BadGateway(VaultError):
    ...


class ParamValidationError(VaultError):
    ...


